name: Publish to IPFS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0,12 * * *' # Republish every 12h

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - name: Initialize
      run: npm init -y
    - name: Install dependencies
      run: npm i ipfs-core ipfs-http-client
    - name: Publish to IPFS & update IPNS
      run: node ./.github/publish.js
      env:
        B58KEY: ${{ secrets.B58IPNS }}
        B32KEY: ${{ secrets.B32IPNS }}
